version: "3.9"
services:
  api:
    build:
      context: .
    ports:
    - 80:80
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    command: flask db upgrade
    volumes:
      - ./docker_config.py:/code/default_config.py
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: flask_app
      POSTGRES_PASSWORD: flask_app_password
      POSTGRES_DB: flask_app
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
